package Calculator;


/**
* Calculator/CalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Thursday, March 2, 2023 1:17:02 PM CET
*/

public interface CalcOperations 
{
  float calculate (int opcode, int op1, int op2);
  void exit ();
} // interface CalcOperations
